version: "3.7"

services:
  bitrix-env:
    container_name: ${PROJECT_NAME}_bitrix-env
    build: ./bitrix-env
    environment:
      TIMEZONE: ${TIMEZONE}
      SSH_PASS: ${SSH_PASS}
      max_allowed_packet: ${max_allowed_packet}
    volumes:
      - ./logs/apache:/var/log/httpd/
      - ./logs/nginx:/var/log/nginx/
      - ./www:/home/bitrix/www
      - ./cert:/home/bitrix/dehydrated/certs/${DOMAIN}
    ports:
      - ${HTTP_PORT}:80
      - ${SSL_PORT}:443
      - ${PUSH_PORTS}:8893-8894
      - ${SSH_PORT}:22
    restart: on-failure
    depends_on: 
      - mysql

  mysql:
    container_name: ${PROJECT_NAME}_mysql
    build: ./mysql
#    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=2
    volumes:
      - ./db:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    restart: on-failure